### ISSUE TITLE
rasterizer is not defined

### ISSUE THREAD

**Issue by BHare1985** [naturalatlas/tilestrata-vtile-raster#1]
Seems like everytime I find a new feature that I want to utilize, you seem to be about 1 week ahead of me in implementing it, it's really coincidental!  I found out that vector tiles may be a good fit for me yesterday, and after about 2 hours of googling I find out you have this. This also happened with jsonp utfgrids too.

Anyways, I am getting an error: rasterizer is not defined. I have npm-installed both tilestrata-vtile-raster and ilestrata-vtile - couldnt find the function anywhere. Here is my server.js 

``` javascript


var tilestrata = require('tilestrata');
var server = tilestrata.createServer();

var args = process.argv.slice(2);

var vtile = require('tilestrata-vtile');
var vtileraster = require('tilestrata-vtile-raster');

var common = {
    xml: 'C:/projects/misc/node-mapnik2/' + args[0],
    tileSize: 256,
    metatile: 1,
    bufferSize: 128
};

server.layer('basemap')
    .route('t.pbf').use(vtile(common))
    .route('t.png').use(vtileraster(common, {
        tilesource: ['basemap', 't.pbf']
    }))
    .route('i.json').use(rasterizer(common, {
        tilesource: ['basemap', 't.pbf'],
        interactivity: true
    }));

// start accepting requests
server.listen(8000, function(err) {
    if (err) console.log(err); 
    }
);

```

On a unrelated note, you may be interested in my fork of Windshaft and getting dynamic mapnik style rendering based on SQL/Requests: https://github.com/BHare1985/Windshaft (The readme is not updated) I know we talked about this before https://github.com/naturalatlas/tilestrata/issues/2

I have it working with Windows for PostGIS and MSSQL (using VC2015RC and mssql plugin). It's using a special VC2015 node_mapnik but the benefit is that it runs newest node-mapnik and newest tilelive and tilelive-mapnik but with grainstore/millstone for creating styles on the fly.

**Comment by brianreavis** [comment]
Hah, awesome! This is another case of a typo in the readme :) Switch that to `vtileraster` and it should work. If you notice anything else janky, I'd love to hear about it – it's a little in the experimental stage.

> On a unrelated note, you may be interested in my fork of Windshaft and getting dynamic mapnik style rendering based on SQL/Requests: https://github.com/BHare1985/Windshaft (The readme is not updated) I know we talked about this before naturalatlas/tilestrata#2

Slick. It'd be really cool to have a dedicated plugin for it one of these days!
