### ISSUE TITLE
cannot accept empty buffer as protobuf

### ISSUE THREAD

**Issue by BHare1985** [naturalatlas/tilestrata-vtile-raster#2]
Accessing a tile by tile.pbf results in a blank file. Accessing it by tile.png results in this error message.

```
C:\projects\misc\node-mapnik2\node_modules\tilestrata-vtile-raster\backend.js:129
                vtile.setData(buffer);
                      ^
Error: cannot accept empty buffer as protobuf
    at Error (native)
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata-vtile-raster\backend.js:129:9
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata-vtile-raster\node_modules\tilestrata-de
pendency\index.js:19:6
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata\lib\TileServer.js:174:4
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata\node_modules\async\lib\async.js:251:17
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata\node_modules\async\lib\async.js:154:25
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata\node_modules\async\lib\async.js:248:21
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata\node_modules\async\lib\async.js:612:34
    at finalizeResult (C:\projects\misc\node-mapnik2\node_modules\tilestrata\lib\TileServer.js:159:4
)
    at C:\projects\misc\node-mapnik2\node_modules\tilestrata\node_modules\async\lib\async.js:607:21

```

**Comment by BHare1985** [comment]
Probably related to this, using your world_merc and test.xml I am getting just white tiles. Looking at the pbf file I get

http://i.imgur.com/6wZnB4h.png

Which is a lot different than what your test fixtures.  It's worth nothing that I pass all tests using `npm test` with both `vtile` and `vtile-raster`

**Comment by BHare1985** [comment]
I realized that `npm test` failed if I went into the folders. I only tested `npm test` seperate by cloning each git and running it.

deleting my `node_modules` folder and doing `npm install tilestrata-vtile` and then `npm install tilestrata-vtile-raster` seems to have fixed the issue. Before I had a previous `tilestrata` which may have caused the issue, needed to be updated maybe. Not sure what he root cause was, just how to fix it right now, leave it open until one of us finds the root cause.

**Comment by BHare1985** [comment]
Spoke too soon, while doing a fresh install fixed the world_merc.shp and test.xml to work properly, my other shape file is causing `cannot accept empty buffer as protobuf` still. Attached is shape file and xml: https://dl.dropboxusercontent.com/u/8518063/ShareX/2015/06/shape.zip

**Comment by brandonreavis** [comment]
Can you zip up your entire project showing how tilestrata-vtile and tilestrata-vtile-raster are setup? I can then try to see whats going on.

I also just added a note to the readme about needing a separate xml for tilestrata-vtile-raster. This could cause blank tiles because mapnik is interpreting the vector tile data as `+proj=longlat +ellps=GRS80 +no_defs` instead of Web Mercator.

**Comment by BHare1985** [comment]
Finally got around to zipping it https://www.dropbox.com/s/rvcomzc3bwo8qa8/tilestrat_nonode.zip?dl=0

run `node server.js txdot.xml`  and open `index.html` to see the error.
then
run `node server.js test.xml`  and open `index.html` to see the world_merc loads fine.

If you need my complete package with node_modules: https://www.dropbox.com/s/bba06ossd68i73b/tilestrata.zip?dl=0

My mapnik binaries are windows specific and need VS2015 RC vcredist here: https://www.microsoft.com/en-us/download/details.aspx?id=46881

**Comment by BHare1985** [comment]
Whatever issue I had back then, is now fixed using the most up-to-date mapnik and tilestrata modules.
